# Set prefix again
unbind C-b
set -g prefix M-s

# Set esc sleep time on 0 (best to which one use vim)
set -s escape-time 0

# Mouse and Vim support 
setw -g mode-keys vi
set-option -g mouse on

# Bind split window map again
unbind "'" 
unbind "%" 
bind "'" splitw -h

# Move cursor focus 
bind k selectp -U
bind j selectp -D
bind h selectp -L
bind l selectp -R

# Resize pane size
bind ^k resizep -U 10
bind ^j resizep -D 10
bind ^h resizep -L 10
bind ^l resizep -R 10

# Kill now active pane and  now use window
bind q killp
bind ^q killw

# Bind select window again
unbind "0"
unbind "1"
unbind "2"
unbind "3"
unbind "4"
unbind "5"
unbind "6"
unbind "7"
unbind "8"
unbind "9"
bind 1 select-window -t 0
bind 2 select-window -t 1
bind 3 select-window -t 2
bind 4 select-window -t 3
bind 5 select-window -t 4
bind 6 select-window -t 5
bind 7 select-window -t 6
bind 8 select-window -t 7
bind 9 select-window -t 8
bind 0 select-window -t 9

# colorscheme

set -g message-style fg='colour222',bg='colour238'
set -g message-command-style fg='colour222',bg='colour238'
set -g pane-border-style fg='colour238'
set -g pane-active-border-style fg='colour154'

set-option -g status-style                 fg=colour15,bg=#282c34
set-option -g pane-border-style            fg=green
set-option -g pane-active-border-style     fg=yellow
set-option -g window-status-activity-style fg=colour111


# statusLine 
set -g set-titles on
set -g status-position top
set -g status-justify 'centre'
set -g status-left-length '100'
set -g status-right-length '100'
# set-window-option -g window-status-format '#[bg=colour238]#[fg=colour107] #I #[bg=colour239]#[fg=colour110] #[bg=colour240]#W#[bg=colour239]#[fg=colour195]#F#[bg=colour238] '
# set-window-option -g window-status-current-format '#[bg=colour236]#[fg=colour215,bold] #I:#[bg=colour235]#[fg=colour167] #[bg=colour234]#W#[bg=colour235]#[fg=colour195]#F#[bg=colour236] '
set-window-option -g window-status-format '#[bg=colour239]#[fg=colour110] #[bg=colour240]#W#[bg=colour239]#[fg=colour195]#F#[bg=colour238] '
set-window-option -g window-status-current-format '#[bg=colour235]#[fg=colour167] #[bg=colour234]#W#[bg=colour235]#[fg=colour195]#F#[bg=colour236] '
set -g status-left '\
#[fg=colour232,bg=#6272a4] %Y-%m-%d \
#[bg=#1b2b34] \
#[fg=colour232,bg=#6272a4] %a %H:%M '
set -g status-right '\
#{?client_prefix,,} \
#[fg=colour232,bg=#6272a4] User: ph \
#[bg=#1b2b34] \
#[fg=colour232,bg=#6272a4] OS: ArchLinux '


# panes split line
set -g pane-border-style fg=magenta
set -g pane-active-border-style "bg=default fg=magenta"
