proxy(){
  export http_proxy=http://127.0.0.1:8889
  export https_proxy=http://127.0.0.1:8889
}


export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup

export EDITOR=nvim
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export ANDROID_HOME=~/Android/Sdk
export GLFW_IM_MODULE=ibus
if [ $TERM = 'alacritty' ]
then
  export TERM=xterm-256color
fi

alias gl='git clone'
alias cl=clear
alias cn=touch
alias mk=mkdir
alias vi=nvim
alias n=neofetch
alias lg=lazygit
alias ra=ranger
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias battery="upower -i `upower -e | grep 'BAT'`"
alias ls=exa
alias l="exa -l"
alias ll="exa -la"


### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
  command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
  command git clone https://hub.fastgit.org/zdharma/zinit "$HOME/.zinit/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

# zinit fast highlight
zinit ice lucid wait='0' atinit='zpcompinit'
zinit light zdharma/fast-syntax-highlighting

zinit wait="1" lucid for \
  OMZ::plugins/autojump/autojump.plugin.zsh\
  OMZ::plugins/fzf/fzf.plugin.zsh\
  OMZ::lib/completion.zsh

  # OMZ::plugins/sudo/sudo.plugin.zsh \

zinit snippet OMZ::lib/history.zsh

# zinit wait='0' lucid for \
#   OMZ::plugins/vi-mode/vi-mode.plugin.zsh
# OMZ::lib/history.zsh

zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode

zinit ice lucid wait='0' atload='_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

zinit ice lucid wait='0' atload='zpcompinit; zpcdreplay'

zinit ice lucid wait='0'
zinit light zsh-users/zsh-completions

zinit ice lucid wait='1'
zinit light Aloxaf/fzf-tab
eval "$(starship init zsh)"

